Feature/tg 99 delete classroom
JU-DEV-LatamBootcamp/Klockan-Backend pull request #33
Opened 2024-02-19 13:40 UTC by pierrecf

# Summary

I implemented the functionality to delete a classroom

# Details

* Created a delete classroom method in classroom repository
* Created a delete clasroom method in classroom services
* Created a delete clasroom controller
* Wrote unit tests for

# Evidence

<img width="642" alt="Screenshot 2024-02-19 at 10 38 15 AM" src="https://github.com/JU-DEV-LatamBootcamp/Klockan-Backend/assets/151547894/3549ab48-67ca-4bcf-9e2f-84b5c19605af">

2024-02-19 13:49 UTC, AndresJavierNazzari requested changes
Before deleting a Classroom we should verify that it has no meetings created, to avoid deleting a classroom that has meetings assigned to it.

2024-02-20 20:03 UTC, pierrecf commented
> Before deleting a Classroom we should verify that it has no meetings created, to avoid deleting a classroom that has meetings assigned to it.

@AndresJavierNazzari Fixed 💯

2024-02-20 21:08 UTC, AndresJavierNazzari commented on KlockanAPI/src/KlockanAPI.Presentation/appsettings.Development.json
>      "AuthorizationUrl": "http://localhost:8080/realms/Klockan/protocol/openid-connect/auth",
Dont change username on DB conection
Check ports, because i think this change with the latest updates on the repo

2024-02-20 21:11 UTC, AndresJavierNazzari commented on KlockanAPI/src/src.sln
> +EndGlobal
why we are including a new sln file?

2024-02-20 21:11 UTC, AndresJavierNazzari commented on KlockanAPI/src/KlockanAPI.Infrastructure/Data/KlockanContext.cs
> +    KlockanContext : DbContext
check the format of the line, it should be in one line
public class KlockanContext : DbContext

2024-02-20 21:11 UTC, AndresJavierNazzari commented on KlockanAPI/src/KlockanAPI.Infrastructure/Repositories/MeetingRepository.cs
>  }
Please add a empty end of line at the end of the file

2024-02-20 21:11 UTC, AndresJavierNazzari commented on KlockanAPI/tests/KlockanAPI.Application.Tests/Services/ClassroomServiceTests.cs
>  }
Please add a empty end of line at the end of the file

2024-02-20 21:11 UTC, AndresJavierNazzari commented on KlockanAPI/src/KlockanAPI.Infrastructure/Repositories/Interfaces/IMeetingRepository.cs
>  }
Please add a empty end of line at the end of the file

2024-02-21 14:10 UTC, AndresJavierNazzari approved these changes

2024-02-21 14:10 UTC, merged